package org.octobot.bot.game.script;

/**
 * ScriptCategory
 *
 * @author Pat-ji
 */
public enum ScriptCategory {
    AGILITY, COMBAT_SLAYER, CONSTRUCTION, FISHING_COOKING, FARMING_HERBLORE, FLETCHING_CRAFTING, HUNTER, MAGIC,
    MINIGAME, MINING_SMITHING, MONEY_MAKING, OTHER, PRAYER, RANGED, RUNECRAFTING, THIEVING, WOODCUTTING_FIREMAKING

}
